language: rust
sudo: false

os:
  - linux
  - osx

rust:
  # There's currently a cargo bug on stable which prevents libfontconfig_sys
  # from building properly. I certainly wish I wrote down what that was.
  - nightly

script:
  - cargo test
