[package]
name = "alacritty"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0"
build = "build.rs"

[[bin]]
doc = false
path = "src/main.rs"
name = "alacritty"

[dependencies]
libc = "*"
cgmath = "0.7"
notify = "2.6"
bitflags = "*"
font = { path = "./font" }
errno = "0.1.6"
parking_lot = { version = "0.3.1", features = ["nightly"] }
serde = "0.8"
serde_yaml = "0.5"
serde_derive = "0.8"
vte = "0.1.2"
mio = "0.6"
serde_json = "*"
copypasta = { path = "./copypasta" }

[features]
default = []
# Enabling this feature makes shaders automatically reload when changed
live-shader-reload = []

[build-dependencies]
gl_generator = "0.5"

[dependencies.glutin]
git = "https://github.com/jwilm/glutin"
rev = "78838c1e1497dc8a1b1c8f69da7a6f3cd7da15c1"


[profile.release]
debug = true
