[package]
name = "alacritty"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies]
servo-fontconfig = "0.2"
freetype = { git = "https://github.com/servo/rust-freetype.git" }
libc = "*"
