[package]
name = "alacritty"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0"
build = "build.rs"

[dependencies]
libc = "*"
cgmath = "0.7"
notify = "2.6"
bitflags = "*"
font = { path = "./font" }
errno = "0.1.6"
parking_lot = { version = "0.3.1", features = ["nightly"] }
serde = "0.8"
serde_yaml = "0.5"
serde_derive = "0.8"
vte = "0.1.2"
mio = "0.6"
copypasta = { path = "./copypasta" }

[features]
default = []
# Enabling this feature makes shaders automatically reload when changed
live-shader-reload = []

[build-dependencies]
gl_generator = "0.5"

[dependencies.glutin]
git = "https://github.com/jwilm/glutin"
rev = "ac3585f7bc8cd56b036de714cccfdc2532f343a7"

[profile.release]
debug = true
