[package]
name = "alacritty"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
license = "Apache-2.0"
exclude = ["res/*"]
build = "build.rs"

[dependencies]
libc = "*"
cgmath = "0.7"
notify = "2.6"
bitflags = "*"
font = { path = "./font" }
errno = "0.1.6"
parking_lot = "0.2.6"
serde = "0.7"
serde_yaml = "0.2"
serde_macros = "0.7"

[build-dependencies]
gl_generator = "0.5"

[dependencies.glutin]
git = "https://github.com/jwilm/glutin"
rev = "22cc23997389bedd948a3ddc3833279ed308a673"
